### ISSUE TITLE
GnuPG

### ISSUE THREAD

**Issue by Sehktel** [Sehktel/Lerning_3IB#4]
Разобраться как работает GunPG

**Comment by podzorovegor** [comment]
Публичный и приватный ключ
![image](https://user-images.githubusercontent.com/95075197/164199537-84a048e7-c6f1-4a8d-a12d-f157db235e5b.png)
Шифрование в ASCII-текстовом формате.
![image](https://user-images.githubusercontent.com/95075197/164199680-ec2e6ec6-c3f6-4a68-abb7-15b8e06f680c.png)
Шифрование файла в бинарном формате
![image](https://user-images.githubusercontent.com/95075197/164199931-7ba211d7-98b8-4a8b-a12a-054f21f3ca60.png)
Раcшифровка файла зашифрованного в формате ASCI
![image](https://user-images.githubusercontent.com/95075197/164200079-675488db-416e-4148-a690-65f647619a57.png)
Раcшифровка файла зашифрованного в бинарном формате
![image](https://user-images.githubusercontent.com/95075197/164200145-e937d148-70ea-40fe-a1b5-bc62270fb04d.png)

**Comment by podzorovegor** [comment]
Инструкция для проверки работоспособности GnuPG
1. Установка GnuPG:
which gpg1 || (apt-get update && apt-get install gpg)
2. Проверка версии:
gpg --version | grep GnuPG
3. Генерация пары ключей(публичный и приватный):
gpg --gen-key
Шаги настройки :1).Выбираем любое имя
2) Любую почту
3) На этом этапе требуется напечатать O
4) Введите пассфразу
4. Просмотр созданных ключей:
1) Публичный ключ - gpg --list-keys
2) Приватный ключ - gpg --list-secret-keys
5. Создание файла, на котором будем применять возможности GnuPG:
nano test.txt # и напишите здесь любой текст
6. Применение шифрования в ASCII формате:
gpg --clearsign test.txt
cat test.txt.asc # проверка
7. Применение шифрование файла в бинарном формате:
gpg -s test.txt
cat test.txt.gpg #проверка
8. Раcшифровка файла зашифрованного в формате ASICI:
gpg -d test.txt.asc > test.txt-decrypt-asci.txt
cat test.txt-decrypt-asci.txt  #проверка
9.Раcшифровка файла зашифрованного в бинарном формате:
gpg -d test.txt.gpg > test.txt-decrypt-bin.txt
cat test.txt-decrypt-bin.txt #проверка
P.S - все вышеперечисленные команды выполнять под рутом/с sudo.

**Comment by Sehktel** [comment]
Требуется проверка

**Comment by Snoork** [comment]
![image](https://user-images.githubusercontent.com/44782837/164977902-6ea977f8-c875-4e65-bde4-f00edf116aee.png)
![image](https://user-images.githubusercontent.com/44782837/164977924-6afbf2b6-6128-4006-af10-a9ebd33d2868.png)
![image](https://user-images.githubusercontent.com/44782837/164977958-7907f16f-c396-45c3-9f92-300da9d4d705.png)
![image](https://user-images.githubusercontent.com/44782837/164977999-dd6e20b6-a5e1-47ec-933f-f003d39bbea4.png)
Тестирование было успешно проведено
