### ISSUE TITLE
Почтовые аккаунт Jenkins

### ISSUE THREAD

**Issue by Sehktel** [Sehktel/Lerning_3IB#7]
После того, как pipeline отработает мы должны отправить уведомление на почту.
Для этого нужна почтовая служба.
Создать почту, проверить, что почтовое уведомление уходит пользователю, а пользователь его получает.

**Comment by podzorovegor** [comment]
![image](https://user-images.githubusercontent.com/95075197/165085413-05349ba7-b993-4854-8d63-e4614bf04888.png)
![image](https://user-images.githubusercontent.com/95075197/165085442-2e879488-0cee-46a9-9833-c7765bc38f4a.png)
